variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io
  skipComponentGovernanceDetection: true

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Build and push Node base images for runtime
      scriptPath: ./build/buildRunTimeImageBases.sh
      imageDir: node
      artifactsFileName: node-runtimeimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Build and push Python base images for build
      scriptPath: ./build/buildBuildImageBases.sh
      imageDir: python
      artifactsFileName: python-buildimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Build and push PHP build base images
      scriptPath: ./build/buildBuildImageBases.sh
      imageDir: php
      artifactsFileName: php-buildimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Build and push PHP runtime base images
      scriptPath: ./build/buildRunTimeImageBases.sh
      imageDir: php
      artifactsFileName: php-runtimeimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Build and push Yarn Cache base image
      scriptPath: ./build/buildBuildImageBases.sh
      imageDir: yarn-cache
      artifactsFileName: yarn-cache-buildimage-bases.txt

- stage: Release
  displayName: Release Stage
  condition: or(succeeded(), failed())
  jobs:
  - template: templates/_releaseBaseImagesJobTemplate.yml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/runtime/node
    - images/build/python
    - images/build/php
    - images/runtime/php
    - images/build/yarn-cache
    - build/
    - vsts/